### ISSUE TITLE
New Yandex IP addrs

### ISSUE THREAD

**Issue by va77** [allmazz/yandex_smart_home_ip#1]
Hi, Noted new IP address of Yandex smart-home in my firewall log file:
141.8.129.64/26
141.8.129.0/26

First time detected at Sun 28 Nov 2021

**Comment by va77** [comment]
And one more subnet from "Tue 25 Jan 2022":
5.255.228.192/26

**Comment by am1ter** [comment]
Hello, @va77 @allmazz. I approve both subnetworks from above, but with more wide range of ip-addresses. So I made the pull request with them.

**Comment by allmazz** [comment]
Hello! Thank you! Now I'll check and merge.

**Comment by allmazz** [comment]
Merged #3
